#!/usr/bin/env bash
# Validate a commit message against docs/COMMIT_MESSAGE_STANDARD.md.
#
# Replaces `uv run validate-commit-msg`. That entry point lived in the fd5-era Python package,
# which no longer exists anywhere in this repo (there is no pyproject.toml or uv.lock), so the
# commit-msg hook failed on EVERY commit — which is why `--no-verify` became the house style and
# took the rest of the gate suite down with it.
#
# Usage: validate-commit-msg.sh <path-to-commit-msg-file>
set -euo pipefail

msg_file="${1:?usage: validate-commit-msg.sh <commit-msg-file>}"

# Strip comment lines (git's editor template), then trailing blank lines.
mapfile -t lines < <(grep -v '^#' "$msg_file")
while [ "${#lines[@]}" -gt 0 ] && [ -z "${lines[-1]}" ]; do
  unset 'lines[-1]'
done

if [ "${#lines[@]}" -eq 0 ]; then
  echo "commit-msg: empty commit message" >&2
  exit 1
fi

subject="${lines[0]}"

# A merge or revert commit generated by git/GitHub is exempt — we do not control its shape.
case "$subject" in
  "Merge "*|"Revert "*) exit 0 ;;
esac

types='feat|fix|docs|chore|refactor|test|ci|build|revert|style'

if ! [[ "$subject" =~ ^($types)(\([a-zA-Z0-9-]+(,[a-zA-Z0-9-]+)*\))?!?:\ .+ ]]; then
  cat >&2 <<EOF
commit-msg: subject does not match the standard.

  got:      $subject
  expected: type(scope)!: short description

  type must be one of: ${types//|/, }
  scope is optional, alphanumeric and hyphens (comma-separated for multiple)
  '!' marks a breaking change

See docs/COMMIT_MESSAGE_STANDARD.md
EOF
  exit 1
fi

if [[ "$subject" =~ \.$ ]]; then
  echo "commit-msg: subject must not end with a period" >&2
  exit 1
fi

# A blank line must separate subject and body.
if [ "${#lines[@]}" -gt 1 ] && [ -n "${lines[1]}" ]; then
  echo "commit-msg: a blank line is required after the subject" >&2
  exit 1
fi

commit_type="${subject%%[(:!]*}"

# `Refs:` is mandatory except for `chore` (per the Exemptions section) and for bot-authored
# dependency bumps, which cannot add one.
refs_optional=0
[ "$commit_type" = "chore" ] && refs_optional=1
[[ "$subject" =~ ^(ci|build)\(deps(-dev)?\): ]] && refs_optional=1

refs_lines=()
for l in "${lines[@]}"; do
  [[ "$l" =~ ^Refs: ]] && refs_lines+=("$l")
done

if [ "${#refs_lines[@]}" -gt 1 ]; then
  echo "commit-msg: only one 'Refs:' line is allowed (found ${#refs_lines[@]})" >&2
  exit 1
fi

if [ "${#refs_lines[@]}" -eq 0 ]; then
  if [ "$refs_optional" -eq 1 ]; then
    exit 0
  fi
  cat >&2 <<EOF
commit-msg: missing mandatory 'Refs:' line for type '$commit_type'.

  Add a last line referencing at least one GitHub issue, e.g.
      Refs: #36
      Refs: #36, REQ-123, RISK-H-02

  'Refs:' is optional only for 'chore' and bot dependency bumps.
See docs/COMMIT_MESSAGE_STANDARD.md
EOF
  exit 1
fi

refs="${refs_lines[0]}"

# The Refs line must be the last non-empty line.
if [ "$refs" != "${lines[-1]}" ]; then
  echo "commit-msg: 'Refs:' must be the last non-empty line" >&2
  exit 1
fi

# At least one GitHub issue reference must be present.
if ! [[ "$refs" =~ \#[0-9]+ ]]; then
  echo "commit-msg: 'Refs:' must include at least one GitHub issue (e.g. #36)" >&2
  echo "  got: $refs" >&2
  exit 1
fi

# Every reference must be a recognised form.
refs_body="${refs#Refs:}"
IFS=',' read -ra items <<<"$refs_body"
for item in "${items[@]}"; do
  ref="$(echo "$item" | xargs)"
  [ -z "$ref" ] && continue
  if ! [[ "$ref" =~ ^(#[0-9]+|(REQ|RISK|SOP)-[A-Za-z0-9-]+)$ ]]; then
    echo "commit-msg: unrecognised reference '$ref' in Refs line" >&2
    echo "  accepted: #123, REQ-..., RISK-..., SOP-..." >&2
    exit 1
  fi
done
