//! Cross-language conformance tests for fd5 Merkle tree hashing.
//!
//! Uses fixture files generated by `tests/conformance/generate_fixtures.py`
//! and expected values from `tests/conformance/expected/*.json`.
//!
//! **Note**: Run with `--test-threads=1` if HDF5 is not built with
//! thread-safety enabled, as the raw `H5Dread` calls for compound
//! datasets are not thread-safe.

use std::path::{Path, PathBuf};

use fd5::verify::Fd5Status;
use fd5::{compute_content_hash, verify as verify_fn};

fn fixtures_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../tests/conformance/fixtures")
        .canonicalize()
        .expect("conformance fixtures directory must exist — run generate_fixtures.py first")
}

fn invalid_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../tests/conformance/invalid")
        .canonicalize()
        .expect("conformance invalid directory must exist — run generate_fixtures.py first")
}

fn expected_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../tests/conformance/expected")
        .canonicalize()
        .expect("conformance expected directory must exist")
}

fn load_expected(name: &str) -> serde_json::Value {
    let path = expected_dir().join(format!("{}.json", name));
    let text = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("Failed to read {}: {}", path.display(), e));
    serde_json::from_str(&text).unwrap()
}

// -----------------------------------------------------------------------
// Valid fixtures: verify() returns Valid
// -----------------------------------------------------------------------

#[test]
fn verify_minimal() {
    let path = fixtures_dir().join("minimal.fd5");
    let expected = load_expected("minimal");
    assert_eq!(expected["verify"], true);

    let status = verify_fn(&path).unwrap();
    assert!(
        matches!(status, Fd5Status::Valid(_)),
        "minimal.fd5 should verify as Valid, got: {:?}",
        status
    );
}

#[test]
fn verify_sealed() {
    let path = fixtures_dir().join("sealed.fd5");
    let expected = load_expected("sealed");
    assert_eq!(expected["verify"], true);

    let status = verify_fn(&path).unwrap();
    assert!(
        matches!(status, Fd5Status::Valid(_)),
        "sealed.fd5 should verify as Valid, got: {:?}",
        status
    );
}

#[test]
fn verify_complex_metadata() {
    let path = fixtures_dir().join("complex-metadata.fd5");
    let expected = load_expected("complex-metadata");
    assert_eq!(expected["verify"], true);

    let status = verify_fn(&path).unwrap();
    assert!(
        matches!(status, Fd5Status::Valid(_)),
        "complex-metadata.fd5 should verify as Valid, got: {:?}",
        status
    );
}

#[test]
fn verify_multiscale() {
    let path = fixtures_dir().join("multiscale.fd5");
    let expected = load_expected("multiscale");
    assert_eq!(expected["verify"], true);

    let status = verify_fn(&path).unwrap();
    assert!(
        matches!(status, Fd5Status::Valid(_)),
        "multiscale.fd5 should verify as Valid, got: {:?}",
        status
    );
}

#[test]
fn verify_tabular() {
    let path = fixtures_dir().join("tabular.fd5");
    let expected = load_expected("tabular");
    assert_eq!(expected["verify"], true);

    let status = verify_fn(&path).unwrap();
    assert!(
        matches!(status, Fd5Status::Valid(_)),
        "tabular.fd5 should verify as Valid, got: {:?}",
        status
    );
}

// -----------------------------------------------------------------------
// with-provenance: may contain external links, expected verify varies
// -----------------------------------------------------------------------

#[test]
fn verify_with_provenance() {
    let path = fixtures_dir().join("with-provenance.fd5");
    let expected = load_expected("with-provenance");
    let should_verify = expected["verify"].as_bool().unwrap();

    let status = verify_fn(&path).unwrap();
    if should_verify {
        assert!(
            matches!(status, Fd5Status::Valid(_)),
            "with-provenance.fd5 should verify as Valid, got: {:?}",
            status
        );
    } else {
        // Expected to not verify (e.g. external links change hash)
        // The file still has a content_hash, just doesn't match
        assert!(
            !matches!(status, Fd5Status::NotFd5),
            "with-provenance.fd5 should be an fd5 file"
        );
    }
}

// -----------------------------------------------------------------------
// Invalid fixtures
// -----------------------------------------------------------------------

#[test]
fn verify_bad_hash_fails() {
    let path = invalid_dir().join("bad-hash.fd5");
    let status = verify_fn(&path).unwrap();
    assert!(
        matches!(status, Fd5Status::Invalid { .. }),
        "bad-hash.fd5 should verify as Invalid, got: {:?}",
        status
    );
}

#[test]
fn verify_no_schema_still_has_hash() {
    // no-schema.fd5 has content_hash but no _schema
    // Verification should still work since it only checks content_hash
    let path = invalid_dir().join("no-schema.fd5");
    let status = verify_fn(&path).unwrap();
    // This file was created with a valid hash, so verify should pass
    assert!(
        matches!(status, Fd5Status::Valid(_)),
        "no-schema.fd5 has valid content_hash, should verify: {:?}",
        status
    );
}

// -----------------------------------------------------------------------
// compute_content_hash matches stored hash
// -----------------------------------------------------------------------

#[test]
fn content_hash_matches_stored_sealed() {
    let path = fixtures_dir().join("sealed.fd5");
    let file = hdf5_metno::File::open(&path).unwrap();
    let stored: String = file
        .attr("content_hash")
        .unwrap()
        .read_scalar::<hdf5_metno::types::VarLenUnicode>()
        .map(|v| v.as_str().to_string())
        .unwrap();
    let computed = compute_content_hash(&file).unwrap();
    assert_eq!(
        computed, stored,
        "Rust compute_content_hash must match stored hash"
    );
}

#[test]
fn content_hash_matches_stored_minimal() {
    let path = fixtures_dir().join("minimal.fd5");
    let file = hdf5_metno::File::open(&path).unwrap();
    let stored: String = file
        .attr("content_hash")
        .unwrap()
        .read_scalar::<hdf5_metno::types::VarLenUnicode>()
        .map(|v| v.as_str().to_string())
        .unwrap();
    let computed = compute_content_hash(&file).unwrap();
    assert_eq!(
        computed, stored,
        "Rust compute_content_hash must match stored hash for minimal"
    );
}

#[test]
fn content_hash_prefix() {
    let path = fixtures_dir().join("sealed.fd5");
    let file = hdf5_metno::File::open(&path).unwrap();
    let computed = compute_content_hash(&file).unwrap();
    assert!(
        computed.starts_with("sha256:"),
        "content_hash must start with 'sha256:'"
    );
    // 7 for "sha256:" + 64 hex chars
    assert_eq!(computed.len(), 71, "content_hash must be sha256: + 64 hex");
}

// -----------------------------------------------------------------------
// Root attributes match expected values
// -----------------------------------------------------------------------

#[test]
fn root_attrs_match_sealed() {
    let expected = load_expected("sealed");
    let path = fixtures_dir().join("sealed.fd5");
    let file = hdf5_metno::File::open(&path).unwrap();

    let root_attrs = &expected["root_attrs"];
    for (key, val) in root_attrs.as_object().unwrap() {
        let attr = file.attr(key).unwrap_or_else(|_| {
            panic!("sealed.fd5 missing expected attribute: {}", key)
        });
        if let Some(expected_str) = val.as_str() {
            let actual: String = attr
                .read_scalar::<hdf5_metno::types::VarLenUnicode>()
                .map(|v| v.as_str().to_string())
                .unwrap();
            assert_eq!(actual, expected_str, "Attribute '{}' mismatch", key);
        }
    }

    // Check prefixed attributes exist with correct prefix
    if let Some(prefixed) = expected.get("root_attrs_prefixed") {
        for (key, prefix_val) in prefixed.as_object().unwrap() {
            let attr = file.attr(key).unwrap_or_else(|_| {
                panic!("sealed.fd5 missing prefixed attribute: {}", key)
            });
            let actual: String = attr
                .read_scalar::<hdf5_metno::types::VarLenUnicode>()
                .map(|v| v.as_str().to_string())
                .unwrap();
            let prefix = prefix_val.as_str().unwrap();
            assert!(
                actual.starts_with(prefix),
                "Attribute '{}' should start with '{}', got '{}'",
                key,
                prefix,
                actual
            );
        }
    }
}
