//! The **ingest conformance corpus** (ADR-0056 §5, ADR-0057 §5) — generic-ingest fixtures whose golden
//! hashes are pinned in `tessera/corpus/ingest-corpus.json`.
//!
//! # Why this exists separately from `tessera-io`'s corpus
//!
//! The existing seal corpus lives in `tessera-io`, which has **no decoders**, so it is feature-invariant
//! by construction. These fixtures need a decoder, so the corpus becomes feature-*conditional* — and a
//! feature-conditional corpus is exactly the shape that passes vacuously. This repo has already shipped
//! that failure: the trycmd docs-as-tests ran **zero cases** in CI for a period, because the `.trycmd`
//! files were not in the crane source filter, and a zero-case pass is indistinguishable from a green
//! run.
//!
//! So [`EXPECTED_COUNTS`] is a **declared count per named configuration**, and the test asserts the
//! count *before* comparing any hash. A `full` build that expects nine fixtures and runs three fails
//! loudly instead of passing quietly.
//!
//! # Source files are generated, never committed
//!
//! ADR-0056 §5 is explicit: the *source* files are generated at build time by a pinned writer, and only
//! the generator descriptor and the resulting golden hashes are committed. Committing binary Parquet
//! would bloat the repo and force golden churn on unrelated dependency bumps. Each fixture here is
//! therefore a `build` function plus the options to ingest what it wrote.
//!
//! The generated file's bytes need no determinism of their own — which is worth stating, because it
//! looks like a gap and is not. `content_hash` is over *our* encoded payload, so it is a function of the
//! extracted logical values only (ADR-0056 §6a Finding 1). `manifest_hash` *is* a function of the
//! generated bytes, via the `ingested_from` source digest, and arrow-rs stamps its own version into a
//! Parquet footer — so a `parquet` bump moves `manifest_hash` and must not move `content_hash`. That is
//! not incidental: it is precisely the §6a value-preservation check, made mechanical.
//!
//! # Hazard coverage
//!
//! ADR-0057 §5's anti-vacuity guard asks for "at least one fixture per live hazard H1–H9". Each fixture
//! declares which it covers in [`IngestFixture::hazards`], and
//! `tests/ingest_corpus.rs::every_live_hazard_has_a_fixture` checks the union — so a hazard cannot
//! quietly lose its coverage when a fixture is edited.

use std::path::{Path, PathBuf};
use std::sync::Arc;

use arrow_array::{
    ArrayRef, BooleanArray, Date32Array, Decimal128Array, Float32Array, Float64Array, Int16Array,
    Int32Array, Int64Array, Int8Array, RecordBatch, StringArray, TimestampMicrosecondArray,
    UInt16Array, UInt32Array, UInt64Array, UInt8Array,
};
use arrow_schema::{DataType, Field, Schema};
use serde::{Deserialize, Serialize};
use tessera_core::manifest::Manifest;
use tessera_core::{Error, Result};

use crate::spec::FormatOptions;

/// Every hazard from ADR-0056 §5 (plus §12a's H10/H11) that a **file-format fixture** can cover.
///
/// The exclusions are all deliberate, and each is a statement about reachability rather than about
/// effort — a hazard listed here that no fixture can actually fail for would be worse than an omission,
/// because `every_live_hazard_has_a_fixture` would then certify a blind spot:
///
/// - **H2** (lossy tile codecs — JPEG-in-TIFF and friends) is *rejected from the normalising path*
///   entirely, so there is nothing to seal and nothing to pin.
/// - **H5** (values under a NULL) is **unreachable through a file format**: Parquet stores no values
///   under its nulls (they are absent, encoded in the definition levels) and a CSV null is an empty
///   field. The hazard exists only at the in-memory arrow boundary, where a library consumer hands us a
///   `RecordBatch` built from a values buffer plus a separate mask — so it is covered by
///   `arrow_table::tests::garbage_under_a_null_is_zeroed_and_recorded` and
///   `canonical::tests::null_slots_are_zeroed_at_the_boundary`, which construct exactly that, and a
///   corpus fixture claiming it would be theatre.
/// - **H6** (NPY endianness) IS covered, by the `ingest_npy_endianness_{le,be}` pair — ADR-0056 §5's
///   named fixture: "a `>f8` file and its `<f8` twin must seal identically".
/// - **H7** (SIMD-dispatched decode) is covered *through* H3/H4, exactly as the ADR's own table says.
pub const LIVE_HAZARDS: &[&str] = &["H1", "H3", "H4", "H6", "H8", "H9", "H10", "H11"];

/// The number of fixtures each named build configuration must run.
///
/// The anti-vacuity guard (ADR-0057 §5). Declared rather than derived on purpose: a count computed from
/// the same predicate the runner uses would agree with the runner by construction and prove nothing.
/// Every configuration named here must be one a build can actually *reach*, or the guard is decorative.
///
/// `--no-default-features` is deliberately **absent**: with no generic lane at all this module does not
/// compile (it needs an arrow writer to generate its sources), and `tests/ingest_corpus.rs` is
/// `#![cfg]`-skipped there. That is not the blind spot the guard exists to close — a corpus that does not
/// build is loud, while a corpus that builds and silently runs three of nine fixtures is not.
pub const EXPECTED_COUNTS: &[(&str, usize)] = &[
    // `default` = arrow + parquet + csv, which is every generic lane P1 ships.
    ("default", 14),
    // `full` and `--all-features` add vendor decoders and the `sql`/`cloud` surfaces; neither adds a
    // generic lane, so the count is unchanged. That invariance is itself the claim: a feature may
    // decide whether a format is readable, never how one encodes.
    ("full", 14),
    ("all-features", 14),
    // `--no-default-features --features parquet` — a real configuration for an embedder who wants the
    // columnar lane without the text one. The two CSV fixtures and the five array ones drop out, and
    // the count says so, which is exactly the case that would otherwise pass while quietly testing less.
    ("parquet-no-csv", 7),
];

/// The committed golden record for one fixture.
///
/// Carries `ingest_decoder` (ADR-0056 §6a's gate requires it, and it lands *with* the first fixture, not
/// after) so a reviewer can tell a decoder bump from a semantic change by reading the diff: a
/// `manifest_hash` that moved next to an `ingest_decoder` that moved is routine; one without is not.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct IngestGolden {
    pub name: String,
    pub product: String,
    /// Cargo features this fixture needs.
    pub requires: Vec<String>,
    /// ADR-0056 §5 hazards this fixture is the coverage for.
    pub hazards: Vec<String>,
    pub id: String,
    pub content_hash: String,
    pub manifest_hash: String,
    /// The sealed decoder triple, lifted out of the recipe bag for reviewability.
    pub ingest_decoder: serde_json::Value,
}

/// The committed corpus file: the declared counts plus one golden per fixture.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct IngestCorpus {
    /// Expected fixture count per named configuration — the anti-vacuity guard.
    pub expected_counts: std::collections::BTreeMap<String, usize>,
    pub fixtures: Vec<IngestGolden>,
}

/// One corpus fixture: how to write its source file, and how to ingest what was written.
pub struct IngestFixture {
    pub name: &'static str,
    /// Cargo features required for this fixture to run at all.
    pub requires: &'static [&'static str],
    /// ADR-0056 §5 hazards this fixture pins.
    pub hazards: &'static [&'static str],
    /// Write the source file into `dir`, returning its path.
    pub build: fn(&Path) -> Result<PathBuf>,
    /// The ingest options for that source file.
    pub options: fn(PathBuf) -> FormatOptions,
}

fn he(e: impl std::fmt::Display) -> Error {
    Error::Invalid(format!("ingest-corpus: {e}"))
}

/// A fixed timestamp. Identity is content-derived, so a corpus fixture must never see a clock.
const TS: &str = "2024-01-01T00:00:00Z";

/// A fixed `ingested_from` label. The generated source lives in a temp dir whose path differs every
/// run, and the path would otherwise land in the sealed edge and move `manifest_hash` per run.
const LABEL: &str = "corpus/ingest";

/// Every fixture, in a fixed order (the corpus file is compared element-wise).
pub fn fixtures() -> Vec<IngestFixture> {
    // The array-lane entries are `#[cfg]`-gated because their *writers* need the `npy` feature (and the
    // `zip` crate it pulls for `.npz`). `BACKENDS_ALL`-style build-invariance does not apply here: a
    // fixture that cannot be built is not a fixture, and `EXPECTED_COUNTS` declares the per-configuration
    // count so a smaller list is checked rather than assumed.
    #[allow(unused_mut)]
    let mut fixtures = vec![
        IngestFixture {
            name: "ingest_parquet_scalars",
            requires: &["parquet"],
            // H11 too: sixteen columns of distinct widths in a fixed order, so a re-encode that sorted
            // them or widened an `Int8` to the machine word would move this fixture.
            hazards: &["H1", "H9", "H11"],
            build: write_scalars,
            options: parquet_opts,
        },
        IngestFixture {
            name: "ingest_parquet_nulls",
            requires: &["parquet"],
            // H10, not H5: what a Parquet round-trip can pin is **nullability-by-presence** — a column
            // declared nullable that contains no null must come out unwrapped, and one that contains a
            // null must come out masked. H5 (producer garbage *under* a null) cannot be expressed in a
            // Parquet file at all; see LIVE_HAZARDS.
            hazards: &["H10"],
            build: write_nulls,
            options: parquet_opts,
        },
        IngestFixture {
            name: "ingest_parquet_floats",
            requires: &["parquet"],
            hazards: &["H4"],
            build: write_floats,
            options: parquet_opts,
        },
        IngestFixture {
            name: "ingest_parquet_dictionary",
            requires: &["parquet"],
            hazards: &["H9"],
            build: write_dictionary,
            options: parquet_opts,
        },
        IngestFixture {
            name: "ingest_parquet_plain_strings",
            requires: &["parquet"],
            hazards: &["H9"],
            build: write_plain_strings,
            options: parquet_opts,
        },
        IngestFixture {
            name: "ingest_parquet_tiny_row_groups",
            requires: &["parquet"],
            hazards: &["H9"],
            build: write_tiny_row_groups,
            options: parquet_opts,
        },
        IngestFixture {
            name: "ingest_arrow_ipc_scalars",
            requires: &["arrow"],
            hazards: &["H9"],
            build: write_arrow_ipc,
            options: arrow_opts,
        },
        IngestFixture {
            name: "ingest_csv_declared",
            requires: &["csv"],
            hazards: &["H3", "H8"],
            build: write_csv,
            options: csv_opts,
        },
        IngestFixture {
            name: "ingest_csv_nulls",
            requires: &["csv"],
            hazards: &["H10"],
            build: write_csv_nulls,
            options: csv_nulls_opts,
        },
    ];
    #[cfg(feature = "npy")]
    fixtures.extend(array_fixtures());
    fixtures
}

/// The array-lane fixtures, split out so the `Vec` above stays a plain literal.
#[cfg(feature = "npy")]
fn array_fixtures() -> Vec<IngestFixture> {
    vec![
        // ── The array lane (ADR-0056 §11) ──
        //
        // The `_le` / `_be` pair is §5's named `ingest_npy_endianness` fixture, split in two because the
        // claim is a RELATION between them: "a `>f8` file and its `<f8` twin must seal identically".
        // `the_endianness_twins_agree_with_each_other` asserts that relation directly, so it holds even
        // in a build where the goldens were just regenerated.
        IngestFixture {
            name: "ingest_npy_endianness_le",
            requires: &["npy"],
            hazards: &["H6"],
            build: write_npy_le,
            options: npy_opts,
        },
        IngestFixture {
            name: "ingest_npy_endianness_be",
            requires: &["npy"],
            hazards: &["H6"],
            build: write_npy_be,
            options: npy_opts,
        },
        IngestFixture {
            name: "ingest_npy_fortran",
            requires: &["npy"],
            // H11 in the array lane: a column-major buffer must be rewritten, not relabelled, or the
            // axes end up wrong instead of the bytes.
            hazards: &["H11"],
            build: write_npy_fortran,
            options: npy_opts,
        },
        IngestFixture {
            name: "ingest_npy_structured",
            requires: &["npy"],
            // The de-interleave is the #193 transpose one format over; H11 because field order and
            // width must survive it exactly.
            hazards: &["H11"],
            build: write_npy_structured,
            options: npy_opts,
        },
        IngestFixture {
            name: "ingest_npz_member",
            requires: &["npy"],
            hazards: &["H9"],
            build: write_npz,
            options: npz_opts,
        },
    ]
}

/// Whether a fixture can run in *this* build.
pub fn enabled(f: &IngestFixture) -> bool {
    f.requires.iter().all(|r| match *r {
        "arrow" => cfg!(feature = "arrow"),
        "parquet" => cfg!(feature = "parquet"),
        "csv" => cfg!(feature = "csv"),
        "npy" => cfg!(feature = "npy"),
        // An unknown predicate must not silently enable a fixture.
        _ => false,
    })
}

/// The fixtures enabled in this build, in corpus order.
pub fn enabled_fixtures() -> Vec<IngestFixture> {
    fixtures().into_iter().filter(enabled).collect()
}

/// Build + ingest one fixture and return its golden record.
///
/// Goes through the ingest **seam** ([`crate::engine::decode_generic_table`] +
/// [`crate::canonical::to_table_product`]) rather than through `engine::run`, and that is a
/// determinism requirement rather than a shortcut. `engine::run` seals an `ingested_via_spec` edge
/// whose digest is over the *parsed spec*, and a spec names its `input` **path** — which for a
/// generated fixture is a temp directory that differs on every run. Sealing it would make
/// `manifest_hash` unreproducible and the §6a value-preservation check unenforceable.
///
/// What is left is exactly the ingest: the source digest, the decoder triple, the transform receipt,
/// the schema and the payload. The spec-engine path is covered by `tests/generic_table.rs` instead.
pub fn golden(f: &IngestFixture, dir: &Path) -> Result<IngestGolden> {
    let input = (f.build)(dir)?;
    let options = (f.options)(input.clone());
    let (source_format, decoder) = crate::engine::generic_source_and_decoder(&options)
        .ok_or_else(|| he(format!("fixture '{}' is not a generic backend", f.name)))?;
    let (m, _payloads) = crate::engine::seal_generic_product(
        &options,
        &crate::canonical::GenericIngest {
            name: f.name,
            timestamp: TS,
            description: "ingest conformance fixture",
            source_format,
            source_path: &input,
            // The generated source lives in a temp dir whose path differs every run; the label is what
            // keeps the sealed `ingested_from` reference stable. (ADR-0040 wants this for PHI hygiene
            // anyway — here it is also what makes the golden reproducible.)
            source_label: Some(LABEL),
            extra_sources: &[],
            decoder,
            generation: None,
            column_meta: &crate::column_meta::ColumnMeta::empty(),
        },
    )?
    .ok_or_else(|| he(format!("fixture '{}' produced no product", f.name)))?;
    Ok(record(f, &m))
}

/// Project a sealed manifest into its golden record.
fn record(f: &IngestFixture, m: &Manifest) -> IngestGolden {
    IngestGolden {
        name: f.name.into(),
        product: m.product.clone(),
        requires: f.requires.iter().map(|s| s.to_string()).collect(),
        hazards: f.hazards.iter().map(|s| s.to_string()).collect(),
        id: m.id.clone(),
        content_hash: m.content_hash.clone().unwrap_or_default(),
        manifest_hash: m.manifest_hash.clone().unwrap_or_default(),
        ingest_decoder: m
            .generation
            .as_ref()
            .and_then(|g| g.config.get(crate::decoder::RECIPE_KEY))
            .cloned()
            .unwrap_or(serde_json::Value::Null),
    }
}

/// Build the whole corpus for this build configuration.
pub fn build(dir: &Path) -> Result<IngestCorpus> {
    let fixtures = enabled_fixtures();
    let mut out = Vec::with_capacity(fixtures.len());
    for f in &fixtures {
        out.push(golden(f, dir)?);
    }
    Ok(IngestCorpus {
        expected_counts: EXPECTED_COUNTS
            .iter()
            .map(|(k, v)| (k.to_string(), *v))
            .collect(),
        fixtures: out,
    })
}

// ── the source writers ────────────────────────────────────────────────────────────────────────

fn parquet_opts(input: PathBuf) -> FormatOptions {
    FormatOptions::Parquet {
        input,
        exclude: Vec::new(),
        column_meta: Default::default(),
    }
}

fn arrow_opts(input: PathBuf) -> FormatOptions {
    FormatOptions::Arrow {
        input,
        exclude: Vec::new(),
        column_meta: Default::default(),
    }
}

fn csv_opts(input: PathBuf) -> FormatOptions {
    FormatOptions::Csv {
        input,
        columns: vec!["id:i4".into(), "x:f8".into(), "label:str".into()],
        delimiter: None,
        header: true,
        null_tokens: Vec::new(),
        exclude: Vec::new(),
        column_meta: Default::default(),
    }
}

fn csv_nulls_opts(input: PathBuf) -> FormatOptions {
    FormatOptions::Csv {
        input,
        columns: vec!["id:i4".into(), "x:f8?".into()],
        delimiter: None,
        header: true,
        null_tokens: vec!["NA".into()],
        exclude: Vec::new(),
        column_meta: Default::default(),
    }
}

/// Write a `RecordBatch` to Parquet with the given writer properties.
fn write_parquet_with(
    dir: &Path,
    name: &str,
    batch: &RecordBatch,
    props: parquet::file::properties::WriterProperties,
) -> Result<PathBuf> {
    let path = dir.join(format!("{name}.parquet"));
    let file = std::fs::File::create(&path).map_err(he)?;
    let mut w = parquet::arrow::ArrowWriter::try_new(file, batch.schema(), Some(props))
        .map_err(|e| he(format!("{name}: {e}")))?;
    w.write(batch).map_err(|e| he(format!("{name}: {e}")))?;
    w.close().map_err(|e| he(format!("{name}: {e}")))?;
    Ok(path)
}

fn field(name: &str, dt: DataType, nullable: bool) -> Field {
    Field::new(name, dt, nullable)
}

/// **H1 + H9** — every accepted scalar type in one table, including the two that carry the timezone
/// hazard (`timestamp(us, None)` and `timestamp(us, "America/New_York")`) and the two that carry a
/// recorded transform (`date32`, `decimal128(18,4)`).
///
/// The tz pair is the fixture that matters most: arrow stores UTC-normalised ticks and the zone is a
/// display annotation, so a decoder that "helpfully" applied a tzdb offset would move this fixture's
/// `content_hash` and nothing else in the suite would notice.
fn write_scalars(dir: &Path) -> Result<PathBuf> {
    let ticks = 1_704_067_200_000_000_i64; // 2024-01-01T00:00:00Z
    let schema = Arc::new(Schema::new(vec![
        field("i8", DataType::Int8, false),
        field("i16", DataType::Int16, false),
        field("i32", DataType::Int32, false),
        field("i64", DataType::Int64, false),
        field("u8", DataType::UInt8, false),
        field("u16", DataType::UInt16, false),
        field("u32", DataType::UInt32, false),
        field("u64", DataType::UInt64, false),
        field("f32", DataType::Float32, false),
        field("f64", DataType::Float64, false),
        field("boolean", DataType::Boolean, false),
        field("text", DataType::Utf8, false),
        field("day", DataType::Date32, false),
        field(
            "naive_ts",
            DataType::Timestamp(arrow_schema::TimeUnit::Microsecond, None),
            false,
        ),
        field(
            "zoned_ts",
            DataType::Timestamp(
                arrow_schema::TimeUnit::Microsecond,
                Some("America/New_York".into()),
            ),
            false,
        ),
        field("amount", DataType::Decimal128(18, 4), false),
    ]));
    let columns: Vec<ArrayRef> = vec![
        Arc::new(Int8Array::from(vec![-128, 0, 127])),
        Arc::new(Int16Array::from(vec![-32768, 0, 32767])),
        Arc::new(Int32Array::from(vec![i32::MIN, 0, i32::MAX])),
        // NOT `[i64::MIN, 0, i64::MAX]`. That shape — a full-width span containing zero — hits #468:
        // vortex 0.75.0 writes different container metadata for it under a debug vs a release build
        // (and x86-64 vs aarch64 release disagree), so the sealed bytes would be a function of the
        // compiler rather than of the data. ±(2^53 + 1) keeps what this column is *for* — a value no
        // `f64` can represent, so an i64 silently routed through a float is still caught — without
        // the pathological span. The pathological shape itself is covered, and its divergence pinned,
        // by `known_limitation_468_full_span_int_container_bytes`.
        Arc::new(Int64Array::from(vec![
            -9_007_199_254_740_993,
            0,
            9_007_199_254_740_993,
        ])),
        Arc::new(UInt8Array::from(vec![0u8, 1, 255])),
        Arc::new(UInt16Array::from(vec![0u16, 1, 65535])),
        Arc::new(UInt32Array::from(vec![0u32, 1, u32::MAX])),
        Arc::new(UInt64Array::from(vec![0u64, 1, u64::MAX])),
        Arc::new(Float32Array::from(vec![-1.5f32, 0.0, 3.25])),
        Arc::new(Float64Array::from(vec![-1.5f64, 0.0, 3.25])),
        Arc::new(BooleanArray::from(vec![true, false, true])),
        Arc::new(StringArray::from(vec!["alpha", "", "ωμέγα"])),
        Arc::new(Date32Array::from(vec![0, 19723, -1])),
        Arc::new(TimestampMicrosecondArray::from(vec![0, ticks, -1])),
        Arc::new(
            TimestampMicrosecondArray::from(vec![0, ticks, -1]).with_timezone("America/New_York"),
        ),
        Arc::new(
            Decimal128Array::from(vec![-1_234_567_i128, 0, 999_999_999_999_999_999_i128])
                .with_precision_and_scale(18, 4)
                .map_err(he)?,
        ),
    ];
    let batch = RecordBatch::try_new(schema, columns).map_err(he)?;
    write_parquet_with(
        dir,
        "scalars",
        &batch,
        parquet::file::properties::WriterProperties::builder().build(),
    )
}

/// **H5** — a nullable column with deliberate garbage under the null.
///
/// Arrow keeps whatever a producer left in a masked slot, so the fixture constructs the arrays by hand
/// (from an `Option` iterator arrow would write zeros) and the seal must be independent of it.
fn write_nulls(dir: &Path) -> Result<PathBuf> {
    let schema = Arc::new(Schema::new(vec![
        field("id", DataType::Int32, false),
        field("maybe_i64", DataType::Int64, true),
        field("maybe_f64", DataType::Float64, true),
        // Declared nullable, contains no null. The H10 half that is easy to get wrong: this column must
        // seal **unwrapped**, because pyarrow, polars and DuckDB disagree about the declaration and
        // honouring it would seal one logical table three ways.
        field("declared_nullable_but_full", DataType::Int32, true),
    ]));
    // Numeric only, deliberately: the table backend carries a validity mask for the fixed-width
    // numeric dtypes only, so a nullable `str` column is rejected at the boundary (with its own unit
    // test in `canonical.rs`) rather than sealed. Extending the mask to `str`/`b1` is an encoder
    // change tracked separately.
    let columns: Vec<ArrayRef> = vec![
        Arc::new(Int32Array::from(vec![1, 2, 3])),
        Arc::new(Int64Array::from(vec![Some(1), None, Some(3)])),
        Arc::new(Float64Array::from(vec![Some(1.5), None, Some(-0.0)])),
        Arc::new(Int32Array::from(vec![Some(4), Some(5), Some(6)])),
    ];
    let batch = RecordBatch::try_new(schema, columns).map_err(he)?;
    write_parquet_with(
        dir,
        "nulls",
        &batch,
        parquet::file::properties::WriterProperties::builder().build(),
    )
}

/// **H4** — the float edge cases the S13 clinical gate is about: `NaN` with a producer-specific
/// payload, `-0.0`, the denormal boundary, and both infinities.
///
/// The NaN payload must be canonicalised (it is uninterpreted producer noise); `-0.0` and the denormals
/// must survive bit-exactly (they are values).
fn write_floats(dir: &Path) -> Result<PathBuf> {
    let odd_nan = f64::from_bits(0x7ff8_0000_dead_beef);
    let schema = Arc::new(Schema::new(vec![field("x", DataType::Float64, false)]));
    let columns: Vec<ArrayRef> = vec![Arc::new(Float64Array::from(vec![
        odd_nan,
        -0.0,
        0.0,
        f64::INFINITY,
        f64::NEG_INFINITY,
        f64::MIN_POSITIVE,
        // The largest subnormal — the value a non-correctly-rounding parser is most likely to move.
        f64::from_bits(0x000f_ffff_ffff_ffff),
    ]))];
    let batch = RecordBatch::try_new(schema, columns).map_err(he)?;
    write_parquet_with(
        dir,
        "floats",
        &batch,
        parquet::file::properties::WriterProperties::builder().build(),
    )
}

/// The low-cardinality string table used by the dictionary pair below.
fn label_batch() -> Result<RecordBatch> {
    let schema = Arc::new(Schema::new(vec![
        field("id", DataType::Int32, false),
        field("label", DataType::Utf8, false),
    ]));
    let columns: Vec<ArrayRef> = vec![
        Arc::new(Int32Array::from(vec![1, 2, 3, 4, 5])),
        Arc::new(StringArray::from(vec![
            "zeta", "alpha", "zeta", "mu", "alpha",
        ])),
    ];
    RecordBatch::try_new(schema, columns).map_err(he)
}

/// **H9 (the dictionary half)** — the same logical table written WITH dictionary encoding.
///
/// Paired with [`write_plain_strings`]: the two fixtures must seal to the same `content_hash`, which is
/// what pins ADR-0056 §2's decision to materialise dictionaries to their *values*. The labels are
/// deliberately not in alphabetical order, so a dictionary built in first-seen order differs from one
/// built sorted — the exact difference between pandas' insertion-time `Categorical` order and another
/// writer's.
fn write_dictionary(dir: &Path) -> Result<PathBuf> {
    write_parquet_with(
        dir,
        "dictionary",
        &label_batch()?,
        parquet::file::properties::WriterProperties::builder()
            .set_dictionary_enabled(true)
            .build(),
    )
}

/// **H9 (the plain half)** — see [`write_dictionary`].
fn write_plain_strings(dir: &Path) -> Result<PathBuf> {
    write_parquet_with(
        dir,
        "plain_strings",
        &label_batch()?,
        parquet::file::properties::WriterProperties::builder()
            .set_dictionary_enabled(false)
            .build(),
    )
}

/// **H9 (the chunking half)** — the same table again, split into two-row row groups.
///
/// Must seal identically to [`write_plain_strings`]: the reader hands the canonicaliser several chunks
/// instead of one, and the fold is where nullability and dtype are resolved, so a bug there would show
/// up only under chunking.
fn write_tiny_row_groups(dir: &Path) -> Result<PathBuf> {
    write_parquet_with(
        dir,
        "tiny_row_groups",
        &label_batch()?,
        parquet::file::properties::WriterProperties::builder()
            .set_max_row_group_row_count(Some(2))
            .set_dictionary_enabled(false)
            .build(),
    )
}

/// **H9 (the container half)** — the same table as Arrow IPC.
///
/// Must seal identically to the Parquet fixtures: the container is not the product.
fn write_arrow_ipc(dir: &Path) -> Result<PathBuf> {
    let path = dir.join("scalars.arrow");
    let batch = label_batch()?;
    let file = std::fs::File::create(&path).map_err(he)?;
    let mut w = arrow_ipc::writer::FileWriter::try_new(file, &batch.schema()).map_err(he)?;
    w.write(&batch).map_err(he)?;
    w.finish().map_err(he)?;
    Ok(path)
}

/// **H3 + H8** — a CSV whose values are the float spellings a non-correctly-rounding or
/// locale-sensitive parser gets wrong.
///
/// Paired with the locale test in `csv_table.rs`: that one proves a hostile `LC_NUMERIC` changes
/// nothing; this one pins the resulting bytes, so a parser swap that changed a last-bit rounding would
/// move a golden rather than pass silently.
fn write_csv(dir: &Path) -> Result<PathBuf> {
    let path = dir.join("declared.csv");
    std::fs::write(
        &path,
        "id,x,label\n\
         1,1.5,alpha\n\
         2,0.1,beta\n\
         3,2.2250738585072011e-308,subnormal-boundary\n\
         4,8.98846567431158e307,near-max\n\
         5,0.500000000000000166533453693773481063544750213623046875,halfway\n\
         6,-0.0,negative-zero\n",
    )
    .map_err(he)?;
    Ok(path)
}

#[cfg(feature = "npy")]
fn npy_opts(input: PathBuf) -> FormatOptions {
    FormatOptions::Npy { input }
}

#[cfg(feature = "npy")]
fn npz_opts(input: PathBuf) -> FormatOptions {
    FormatOptions::NpzMember {
        input,
        member: "energy.npy".into(),
    }
}

#[cfg(feature = "npy")]
/// Write a minimal `.npy` (v1.0) with the given descriptor, shape and payload.
fn write_npy_file(
    dir: &Path,
    name: &str,
    descr: &str,
    fortran: bool,
    shape: &[u64],
    payload: &[u8],
) -> Result<PathBuf> {
    let path = dir.join(format!("{name}.npy"));
    std::fs::write(&path, npy_bytes(descr, fortran, shape, payload)).map_err(he)?;
    Ok(path)
}

#[cfg(feature = "npy")]
/// The `.npy` byte sequence — shared with the `.npz` writer below.
fn npy_bytes(descr: &str, fortran: bool, shape: &[u64], payload: &[u8]) -> Vec<u8> {
    let shape_text = if shape.len() == 1 {
        format!("({},)", shape[0])
    } else {
        format!(
            "({})",
            shape
                .iter()
                .map(|d| d.to_string())
                .collect::<Vec<_>>()
                .join(", ")
        )
    };
    let header = format!(
        "{{'descr': {descr}, 'fortran_order': {}, 'shape': {shape_text}, }}\n",
        if fortran { "True" } else { "False" }
    );
    let mut out = Vec::new();
    out.extend_from_slice(b"\x93NUMPY");
    out.extend_from_slice(&[1, 0]);
    out.extend_from_slice(&(header.len() as u16).to_le_bytes());
    out.extend_from_slice(header.as_bytes());
    out.extend_from_slice(payload);
    out
}

#[cfg(feature = "npy")]
/// The float values both endianness twins carry — deliberately including the edge cases S13 guarantees.
const TWIN_VALUES: [f64; 5] = [1.5, -0.5, 0.0, 1e-300, f64::MIN_POSITIVE];

#[cfg(feature = "npy")]
/// **H6** — the little-endian half of ADR-0056 §5's `ingest_npy_endianness` fixture.
fn write_npy_le(dir: &Path) -> Result<PathBuf> {
    let payload: Vec<u8> = TWIN_VALUES.iter().flat_map(|x| x.to_le_bytes()).collect();
    write_npy_file(dir, "twin_le", "'<f8'", false, &[5], &payload)
}

#[cfg(feature = "npy")]
/// **H6** — the big-endian twin. Different bytes, identical values, so it must seal the same
/// `content_hash` as [`write_npy_le`]. A naive `cast_slice` of this buffer produces garbage that looks
/// like data, which is why the hazard is rated *low × fatal*.
fn write_npy_be(dir: &Path) -> Result<PathBuf> {
    let payload: Vec<u8> = TWIN_VALUES.iter().flat_map(|x| x.to_be_bytes()).collect();
    write_npy_file(dir, "twin_be", "'>f8'", false, &[5], &payload)
}

#[cfg(feature = "npy")]
/// A Fortran-ordered 2×3 matrix. Must be **rewritten** to C order and recorded, not relabelled by
/// reversing the shape (which would make the axes wrong instead of the bytes).
fn write_npy_fortran(dir: &Path) -> Result<PathBuf> {
    // The matrix [[1,2,3],[4,5,6]] in column-major order.
    let f_order = [1.0f64, 4.0, 2.0, 5.0, 3.0, 6.0];
    let payload: Vec<u8> = f_order.iter().flat_map(|x| x.to_le_bytes()).collect();
    write_npy_file(dir, "fortran", "'<f8'", true, &[2, 3], &payload)
}

#[cfg(feature = "npy")]
/// A structured/record dtype — which is a **table**, not an array (ADR-0056 §1/§11). NumPy stores records
/// interleaved, so the fixture pins the de-interleave.
fn write_npy_structured(dir: &Path) -> Result<PathBuf> {
    let mut payload = Vec::new();
    for (i, f) in [(1i32, 1.5f64), (-2, -0.25), (3, 7.0)] {
        payload.extend_from_slice(&i.to_le_bytes());
        payload.extend_from_slice(&f.to_le_bytes());
    }
    write_npy_file(
        dir,
        "records",
        "[('id', '<i4'), ('energy', '<f8')]",
        false,
        &[3],
        &payload,
    )
}

#[cfg(feature = "npy")]
/// A `.npz` archive — a zip of `.npy` members, STORED like `np.savez`.
fn write_npz(dir: &Path) -> Result<PathBuf> {
    let path = dir.join("bundle.npz");
    let values = [511.0f64, 7.25, -0.5];
    let payload: Vec<u8> = values.iter().flat_map(|x| x.to_le_bytes()).collect();
    let member = npy_bytes("'<f8'", false, &[3], &payload);
    let file = std::fs::File::create(&path).map_err(he)?;
    let mut w = zip::ZipWriter::new(file);
    let opts: zip::write::FileOptions<'_, ()> =
        zip::write::FileOptions::default().compression_method(zip::CompressionMethod::Stored);
    zip::ZipWriter::start_file(&mut w, "energy.npy", opts).map_err(he)?;
    std::io::Write::write_all(&mut w, &member).map_err(he)?;
    w.finish().map_err(he)?;
    Ok(path)
}

/// **H5 (the CSV half)** — declared NULL tokens plus the always-NULL empty field.
fn write_csv_nulls(dir: &Path) -> Result<PathBuf> {
    let path = dir.join("nulls.csv");
    std::fs::write(&path, "id,x\n1,1.0\n2,\n3,NA\n4,4.0\n").map_err(he)?;
    Ok(path)
}
